### ISSUE TITLE
Generate releases on pulls to Master

### ISSUE THREAD

**Issue by Milkshak3s** [Imperium-Tech/imperium-shipyard#31]
Users should be able to run this locally without pulling a repo & running a script to get a GUI. We can add a CI job to build windows binaries, tag releases, and deploy the bin & zip from the job to those releases, so there's no deploy work on the dev's side, aside from modifying release numbers appropriately.

**Comment by Milkshak3s** [comment]
Yeah so generating binaries from Python is actually trash, so we'll release a zip with a clear readme and execution steps in the readme instead.

**Comment by qu-gg** [comment]
Addressed using auto-py-to-exe to generate the EXE for Windows.
Users on Linux/MacOS can simply set the script to exec and run it from the root of the repo.

**Comment by qu-gg** [comment]
Due to the broken link in #47 , automated releases through CI is unavailable. Presently will just do manual releases.
